name: Create Issue on Push

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Create a new issue
      - name: Create a new issue
        uses: peter-evans/create-issue@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Test Issue for Commit"
          body: |
            A new issue has been created to test the changes for the latest push.
            
            **Commit Details:**
            - Commit Author: ${{ github.actor }}
            - Commit Message: ${{ github.event.head_commit.message }}
            - Commit URL: ${{ github.event.head_commit.url }}

